---
- name: Change the hostname of Networking Devices
  hosts: routers:switches
  connection: ansible.netcommon.network_cli
  gather_facts: no  # Set to no because we are using ios_facts module

  tasks:
    - name: Set New Hostname
      ios_config:
        lines:
          - "hostname {{device_hostname}}"
      register: set_hostname_result

